import os
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field
from core.llm_factory import get_llm  # Centralized LLM factory with fallbacks


# ---------------------------------------------------------------------------
# 1. STRUCTURED OUTPUT SCHEMA
# ---------------------------------------------------------------------------
class StreamlitFormCodeResponse(BaseModel):
    form_code: str = Field(
        description=(
            "ONLY the Python code that builds the KYC form fields, validation, "
            "and submission handling (the body that goes inside `with st.form(...)`, "
            "plus the `if submitted:` block below it). Do NOT include imports, "
            "`st.set_page_config`, the CSS `st.markdown` block, or any other "
            "page boilerplate — those already exist and are provided separately. "
            "`st`, `re`, and `submit_to_pipeline` are already defined and in "
            "scope. Do NOT include markdown code fences (```) or commentary."
        )
    )


# ---------------------------------------------------------------------------
# 2. SHARED DESIGN SYSTEM CSS (HIGH-CONTRAST ENFORCED)
# ---------------------------------------------------------------------------
DESIGN_SYSTEM_CSS = """
<style>
    /* Dark slate overall app background */
    .stApp {
        background-color: #0f172a !important;
        color: #f8fafc !important;
    }

    /* Form container styling */
    div[data-testid="stForm"] {
        border: 1px solid #334155 !important;
        border-radius: 12px !important;
        background-color: #1e293b !important;
        padding: 24px !important;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }

    /* 1. INPUT FIELD LABELS (Fixes dark grey unreadable labels) */
    .stTextInput label, .stTextArea label, .stSelectbox label,
    .stNumberInput label, .stDateInput label, div[data-testid="stMarkdownContainer"] p {
        color: #e2e8f0 !important;
        font-weight: 600 !important;
        font-size: 0.95rem !important;
    }

    /* 2. ALL INPUT FIELDS (Text, Date, Select, Number, Textarea) */
    div[data-baseweb="input"] input,
    div[data-baseweb="textarea"] textarea,
    div[data-baseweb="select"] div,
    .stTextInput input,
    .stTextArea textarea,
    .stDateInput input,
    .stNumberInput input,
    .stSelectbox div[role="combobox"] {
        background-color: #1e293b !important;
        color: #ffffff !important;
        -webkit-text-fill-color: #ffffff !important;
        border-radius: 8px !important;
        border: 1px solid #475569 !important;
        font-weight: 500 !important;
    }

    /* 3. INPUT FOCUS STATES */
    div[data-baseweb="input"]:focus-within,
    div[data-baseweb="textarea"]:focus-within {
        border-color: #6366f1 !important;
    }

    /* 4. PLACEHOLDER TEXT CONTRAST */
    textarea::placeholder, input::placeholder {
        color: #94a3b8 !important;
        -webkit-text-fill-color: #94a3b8 !important;
    }

    /* 5. PRIMARY SUBMIT BUTTONS */
    div.stButton > button, div[data-testid="stFormSubmitButton"] > button {
        width: 100%;
        background-color: #4f46e5 !important;
        color: #ffffff !important;
        -webkit-text-fill-color: #ffffff !important;
        border-radius: 8px !important;
        font-weight: 700 !important;
        border: none !important;
        padding: 10px 16px !important;
        transition: all 0.2s ease-in-out;
    }

    div.stButton > button:hover, div[data-testid="stFormSubmitButton"] > button:hover {
        background-color: #4338ca !important;
        color: #ffffff !important;
    }
</style>
"""

# Markers used to splice the LLM-generated form code into the static shell,
# and to extract just that portion back out of an existing streamlit_app.py
# for incremental (Jira-story-scoped) regeneration.
FORM_BEGIN_MARKER = "# ===== BEGIN GENERATED FORM ====="
FORM_END_MARKER = "# ===== END GENERATED FORM ====="


def build_streamlit_shell(form_code: str) -> str:
    """Assembles the full streamlit_app.py from the static page shell (page
    config + design-system CSS, never regenerated by the LLM) and the
    LLM-generated form body. Keeping the shell static means every Agent 02
    run only needs to generate/regenerate the small form-specific part
    instead of the whole file — far fewer tokens, no risk of the LLM
    truncating a multi-thousand-character CSS string it re-types every time.
    """
    return f'''import re
import json
import streamlit as st
import requests

# The one live, already-verified ingestion pipeline (ETL cleanse -> DuckDB ->
# MDM golden-record upsert). The generated form below submits here over HTTP
# instead of importing a freshly-(re)generated ETL function directly, so it
# reaches the FULL pipeline — including Agent 04/MDM — reliably, using the
# same stable backend contract regardless of what Agent 03 most recently
# generated.
API_INGEST_URL = "http://127.0.0.1:8000/api/ingest"


def submit_to_pipeline(form_data: dict) -> dict:
    """Posts form_data to the ingestion API. Values from Streamlit widgets
    (e.g. `date` from st.date_input, `Decimal`-like numbers) aren't always
    JSON-serializable as-is, and generated form code doesn't reliably
    remember to convert every field correctly — so serialization happens
    here once, centrally, with `default=str` as a catch-all for any type
    json.dumps doesn't natively support."""
    try:
        payload = json.dumps(form_data, default=str)
        resp = requests.post(
            API_INGEST_URL,
            data=payload,
            headers={{"Content-Type": "application/json"}},
            timeout=20,
        )
        return resp.json()
    except Exception as e:
        return {{"status": "error", "message": f"Could not reach the ingestion API: {{e}}"}}


st.set_page_config(page_title="KYC Portal", page_icon="🤖", layout="wide")

st.markdown("""{DESIGN_SYSTEM_CSS}""", unsafe_allow_html=True)

{FORM_BEGIN_MARKER}
{form_code.strip()}
{FORM_END_MARKER}
'''


def extract_form_code(existing_file_content: str) -> str | None:
    """Pulls just the previously-generated form body back out of an existing
    streamlit_app.py, so incremental Agent 02 runs only need to hand the LLM
    the small part that actually changes, not the whole file."""
    if FORM_BEGIN_MARKER not in existing_file_content or FORM_END_MARKER not in existing_file_content:
        return None
    start = existing_file_content.index(FORM_BEGIN_MARKER) + len(FORM_BEGIN_MARKER)
    end = existing_file_content.index(FORM_END_MARKER)
    if end <= start:
        return None
    return existing_file_content[start:end].strip()


# ---------------------------------------------------------------------------
# 3. MAIN UI CODE GENERATION FUNCTION
# ---------------------------------------------------------------------------
def generate_ui_form_code(ui_details: str, existing_form_code: str = None) -> str:
    """Generates or incrementally updates ONLY the KYC form body, based on the
    scope of the current Jira UI story — not the whole page."""
    structured_llm = get_llm(schema=StreamlitFormCodeResponse)

    system_prompt = """
You are an expert Enterprise Python Streamlit UI engineer.
Generate ONLY the form-building code requested below — not a full page.

SCOPE RULES (STRICT):
1. Output ONLY the code that goes inside `with st.form("kyc_form"): ...` plus
   the `if submitted:` handling block that follows it. Do NOT output imports,
   `st.set_page_config`, or any CSS/`st.markdown` styling block — the page
   shell already provides all of that, and `st`, `re`, and
   `submit_to_pipeline` are already defined and in scope.
   REQUIRED: the LAST line inside the `with st.form(...)` block must be
   exactly `submitted = st.form_submit_button("Submit")` — this variable is
   what the `if submitted:` check outside the form depends on.
2. LIVE PIPELINE INTEGRATION: On submission, call the shared
   `submit_to_pipeline(form_data)` helper — do NOT call `requests.post`
   directly, and do NOT convert field values yourself (e.g. no
   `.isoformat()`); `submit_to_pipeline` already handles JSON-safe
   serialization for any value type a widget can return:
   ```
   if submitted:
       form_data = {{...collected field values, using the EXACT keys from
                    the "CANONICAL FIELD NAMES" list below, passed as-is —
                    e.g. a date_input's raw `date` value, not a string...}}
       res = submit_to_pipeline(form_data)
       if res.get("status") == "success":
           st.success(res.get("message", "Submitted successfully."))
       else:
           st.warning(res.get("message", "Submitted, but one stage reported an issue."))
   ```
   CANONICAL FIELD NAMES — use these exact dict keys in `form_data` for any
   field you collect (the backend's cleansing/masking/risk-scoring logic
   keys off these names specifically): `full_name`, `dob`, `email`, `phone`,
   `aadhaar_no` (the 12-digit Aadhaar field — always name it this, not
   `aadhaar` or `adhaar`), `address_line1`, `address_line2`, `city`,
   `state`, `pincode`, `employment_type`, `annual_income`, `credit_score`,
   `terms_accepted` (a real Python `bool` — `True`/`False` from
   `st.checkbox(...)` directly, NEVER the string `"yes"`/`"no"`). Only
   include the keys for fields this Jira story actually asks for.
3. LAYOUT: Organize inputs using `st.columns(2)` or `st.columns(3)` inside
   the form for a clean multi-column layout.
4. INCREMENTAL CHANGES ONLY: If existing form code is provided below, treat
   the new specification as a DELTA against it — add only the newly
   requested fields/validation and remove only what's explicitly no longer
   needed, preserving every other field, key name, and validation rule
   exactly as-is. Do NOT rewrite fields that weren't asked to change.
5. VALIDATION: Implement real-time regex checks for sensitive inputs (e.g.,
   Aadhaar must be exactly 12 digits) and render `st.error()` for invalid
   input before submitting to the API.
6. ONLY use these real Streamlit widget calls, and ONLY the keyword
   arguments shown — NEVER invent a method or kwarg that doesn't exist
   (e.g. there is no `st.read_only`, and `st.text_input` has no `validate`
   kwarg — do not pass one):
   `st.text_input(label, value=..., placeholder=..., disabled=...)`,
   `st.number_input(label, value=..., min_value=..., max_value=...)`,
   `st.date_input(label, value=...)`, `st.selectbox(label, options=...)`,
   `st.multiselect(label, options=...)`, `st.checkbox(label, value=...)`,
   `st.text_area(label, value=...)`, `st.error(msg)`, `st.success(msg)`,
   `st.warning(msg)`, `st.form_submit_button(label)`. For a read-only or
   computed field, use `st.text_input(label, value=computed_value,
   disabled=True)`. Do all validation with plain `if`/`re.match` checks and
   `st.error(...)` after the widget call — never via a widget kwarg.
7. Keep the code simple: avoid deeply nested expressions or long chained
   parentheses (a common source of syntax errors) — prefer intermediate
   variables over one-line compound expressions.
"""

    context_prefix = ""
    if existing_form_code and existing_form_code.strip():
        context_prefix = (
            "====================================================================\n"
            "CURRENT FORM CODE (make the smallest possible diff against this):\n"
            "====================================================================\n"
            f"{existing_form_code}\n\n"
            "====================================================================\n\n"
        )

    human_prompt = f"{context_prefix}JIRA STORY / REQUESTED CHANGE:\n{ui_details}"

    response: StreamlitFormCodeResponse = structured_llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=human_prompt),
    ])

    return response.form_code
