# core/ui_server.py
"""Manages the Streamlit process that serves Agent 02's generated
streamlit_app.py on port 8502 — the single live UI for Workflow 2.

There used to be two separate, duplicate "launch if not already running"
implementations (one in app.py, one in Agent 02's own orchestrator), and
neither of them ever restarted an already-running server. That meant a
freshly (re)generated streamlit_app.py just sat on disk unapplied until
Streamlit's own file-watcher noticed and prompted the user to click
"Rerun" — so a UI regenerated by Agent 02 didn't actually take effect
without a manual step. This module is the single implementation both
callers now share, and `restart_ui_server` always kills whatever is
currently on the port and launches a fresh process against the latest
file, so newly generated code is live immediately.
"""
import subprocess
import sys
import time
from pathlib import Path

import requests

PROJECT_ROOT = Path(__file__).resolve().parent.parent
UI_FILE_PATH = PROJECT_ROOT / "streamlit_app.py"
UI_PORT = 8502


def is_ui_server_healthy(port: int = UI_PORT, timeout: float = 1.5) -> bool:
    try:
        resp = requests.get(f"http://127.0.0.1:{port}/_stcore/health", timeout=timeout)
        return resp.status_code == 200
    except Exception:
        return False


def _kill_process_on_port(port: int) -> None:
    """Best-effort kill of whatever process is listening on `port`. Silently
    no-ops if nothing is listening or the platform tooling isn't available —
    this is cleanup, not a step that should ever block a UI regeneration."""
    try:
        if sys.platform == "win32":
            result = subprocess.run(
                ["powershell", "-NoProfile", "-Command",
                 f"(Get-NetTCPConnection -LocalPort {port} -ErrorAction SilentlyContinue).OwningProcess"],
                capture_output=True, text=True, timeout=10,
            )
            pids = {p.strip() for p in result.stdout.splitlines() if p.strip().isdigit() and p.strip() != "0"}
            for pid in pids:
                subprocess.run(
                    ["powershell", "-NoProfile", "-Command", f"Stop-Process -Id {pid} -Force -ErrorAction SilentlyContinue"],
                    capture_output=True, timeout=10,
                )
        else:
            result = subprocess.run(["lsof", "-ti", f":{port}"], capture_output=True, text=True, timeout=10)
            for pid in result.stdout.split():
                subprocess.run(["kill", "-9", pid], capture_output=True, timeout=10)
    except Exception as e:
        print(f"[ui_server] Non-fatal: couldn't kill existing process on port {port}: {e}")


def restart_ui_server(port: int = UI_PORT, max_wait_attempts: int = 20) -> bool:
    """Kills whatever is on `port` (if anything) and launches a fresh
    `streamlit run streamlit_app.py` against the current file on disk.
    Returns True once the new server responds healthy."""
    if not UI_FILE_PATH.exists():
        return False

    _kill_process_on_port(port)
    time.sleep(1.0)  # give the OS a moment to actually free the port

    # Invoke via `sys.executable -m streamlit` rather than a bare `"streamlit"`
    # command — the latter depends on the venv's Scripts/bin dir being on
    # PATH, which it isn't unless the venv was actually `activate`d in the
    # parent shell (it usually isn't, e.g. when this process itself was
    # launched via `.venv/Scripts/python.exe -m streamlit run app.py`).
    subprocess.Popen(
        [
            sys.executable, "-m", "streamlit", "run", "streamlit_app.py",
            "--server.port", str(port),
            "--server.headless", "true",
        ],
        cwd=PROJECT_ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    for _ in range(max_wait_attempts):
        time.sleep(0.5)
        if is_ui_server_healthy(port, timeout=1.0):
            return True
    return False


def ensure_ui_server_running(ui_code: str = None, port: int = UI_PORT, max_retries: int = 3) -> bool:
    """Health-check first; only launches (doesn't restart) if nothing is
    currently serving the port. Used for the dashboard's manual
    "Start / Launch" button, where an already-running, already-current
    server shouldn't be torn down for no reason."""
    if is_ui_server_healthy(port):
        return True

    if not UI_FILE_PATH.exists() and ui_code and ui_code.strip():
        with open(UI_FILE_PATH, "w", encoding="utf-8") as f:
            f.write(ui_code)

    if not UI_FILE_PATH.exists():
        return False

    for _ in range(max_retries):
        if restart_ui_server(port):
            return True
    return False
