# scripts/generate_docs.py
import sys
from pathlib import Path

# Resolve project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# Imports from core state
from core.state import ProjectState

def generate_mermaid_diagram() -> str:
    """Dynamically builds Mermaid flowchart markdown from system inspects."""
    # Read fields dynamically from the Pydantic model contract
    state_fields = list(ProjectState.model_fields.keys())
    
    mermaid_code = f"""# System Architecture & Flowchart

> *This document is automatically generated by `scripts/generate_docs.py`. Do not edit manually.*

```mermaid
flowchart TD
    %% Styling
    classDef stateNode fill:#eceff1,stroke:#37474f,stroke-width:2px;
    classDef agentNode fill:#e3f2fd,stroke:#1565c0,stroke-width:2px;
    classDef outputNode fill:#e8f5e9,stroke:#2e7d32,stroke-width:2px;

    %% Memory State
    State["ProjectState (RAM)<br/>Fields: {', '.join(state_fields)}"]:::stateNode

    %% Agent Flow
    A1["Agent 01: Requirements Engine"]:::agentNode
    A2["Agent 02: UI Engine"]:::agentNode
    A3["Agent 03: ETL Engine"]:::agentNode
    A4["Agent 04: MDM Engine"]:::agentNode

    %% Execution Graph
    Start([User Input]) --> A1
    A1 -->|Updates current_schema| State
    State --> A2
    A2 -->|Generates ui_code| State
    State --> A3
    A3 -->|Generates etl_code| State
    State --> A4
    A4 -->|Generates mdm_ddl| State

    %% File Artifacts
    State -.-> AppPy["app.py"]:::outputNode
    State -.-> EtlPy["etl.py"]:::outputNode
    State -.-> SchemaSql["schema.sql"]:::outputNode

    """
    return mermaid_code

def main():
    # 1. Define target path
    docs_file = PROJECT_ROOT / "docs" / "architecture_flowchart.md"

    # 2. Ensure /docs folder exists
    docs_file.parent.mkdir(parents=True, exist_ok=True)

    # 3. Generate string content
    content = generate_mermaid_diagram()

    # 4. Write string content into docs/architecture_flowchart.md
    docs_file.write_text(content)
    print(f"Successfully auto-updated flowchart documentation at: {docs_file}")

# Execute main() when running script directly from terminal
if __name__ == "__main__":
    main()